export const DemoFormOptions = {
  GENDER: [
    'Male',
    'Female',
    'Other',
    'Prefer not to say',
  ],
  MARITAL_STATUS: [
    'Single',
    'Married',
    'Divorced',
    'Widowed',
    'Separated',
  ],
  RESIDENCY_STATUS: [
    'Resident Indian',
    'NRI',
    'PIO',
    'OCI',
    'Foreign national',
  ],
  OCCUPATION: [
    'Salaried',
    'Self-Employed',
    'Business',
    'Professional',
    'Retired',
    'Student',
    'Homemaker',
    'Other',
  ],
  INDIAN_STATES_AND_UTS: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
  ],
};
